# Some variables have default fallback values.
# If not specified in this file, the program will use these fallback values.

[General]
    # Looping Method
    # This specifies how the program will check for changes in the IP address.
    # Have four options:
    # - `intervalTime`: Check for changes at regular intervals.
    # - `onChange`: Check for changes only when the IP address changes.
    # - `dateTime`: Check for changes at specific times of the day.
    # - `onStart`: Check for changes only when the program starts.
    # Note: The `onChange`, `dateTime`, and `onStart` methods not available yet.
    # ;; Fallback default: intervalTime
    loopingMethod = "intervalTime"

    # The interval time specifies the time (in minutes) between each loop check and update.
    # This value is used if no custom `intervalTime` is provided by the program.
    # ;; Fallback default: 800
    intervalTime = 800

[CloudFlare]
    # Enable or disable CloudFlare API integration
    enabled = False

    # Email address associated with the CloudFlare account
    email = "YOUR_EMAIL_OF_CLOUDFLARE"

    # API Token (not a password). Generate from: https://dash.cloudflare.com/profile/api-tokens
    password = "YOUR_GLOBAL_OR_LOCAL_API_KEY"

    # Fully Qualified Domain Name (FQDN)
    # Specify the list of hostnames or domains for dynamic updates (e.g., "dynamic.me.com" or "me.com").
    # Note: FQDNv4 and FQDNv6 are used for IPv4 and IPv6 addresses, respectively.
    # FQDNv4: List of hostnames or domains for IPv4 addresses.
    # FQDNv6: List of hostnames or domains for IPv6 addresses.
    # Note: You can specify the same FQDN for both IPv4 and IPv6, or use different ones.
    FQDNv4 = ["dynamic.me.com","me.com"]
    FQDNv6 = ["dynamic.me.com","me.com"]

    # API Cache Settings (referred to as `RecordsCache`):
    # - `cacheTimeout`: Duration (in seconds) for caching API responses before refreshing.
    # - Set to -1 for unlimited caching (reuse the same cache indefinitely).
    # - Set to 0 to disable caching (fetch data on every API call).
    # ;; Fallback default: 172800 (48 hours or 2 days)
    cacheTimeout = 172800

    # Persistent Cache
    # If enabled, cached data will persist even if the program exits unexpectedly
    # (e.g., due to errors, exceptions, or manual termination). The cached data
    # will remain valid until its expiry time.
    # Note: This may increase storage usage and is recommended for slow or low-end
    # hardware to enhance performance.
    # ;; Fallback default: False
    cachePersistent = False

[NoIP]
    # This API is currently under development and not yet available for release.
    # Enabling it will not function as expected.

    # Enable or disable NoIP API integration.
    enabled = False
    
    # username associated with the NoIP account.
    username = "YOUR_USERNAME_OF_NOIP"

    # password associated with the NoIP account.
    password = "YOUR_PASSWOPD_OF_NOIP"

    # Fully Qualified Domain Name (FQDN)
    # Specify the list of hostnames or domains for dynamic updates (e.g., "dynamic.me.com" or "me.com").
    FQDN = ["dynamic.me.com","me.com"]

[DynDNS]
    # This API is currently under development and not yet available for release.
    # Enabling it will not function as expected.

    # Enable or disable DynDNS API integration.
    enabled = False
    
    # username associated with the DynDNS account.
    username = "YOUR_USERNAME_OF_NOIP"

    # password associated with the DynDNS account.
    password = "YOUR_PASSWOPD_OF_NOIP"

    # Fully Qualified Domain Name (FQDN)
    # Specify the list of hostnames or domains for dynamic updates (e.g., "dynamic.me.com" or "me.com").
    FQDN = ["dynamic.me.com","me.com"]
